# Generated by Django 4.2.7 on 2023-11-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='scores_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
