# Generated by Django 4.2.7 on 2023-11-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_scores_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
